flagCountries = {
    "British": "https://flagsapi.com/GB/flat/64.png",
    "German": "https://flagsapi.com/DE/flat/64.png",
    "Spanish": "https://flagsapi.com/ES/flat/64.png",
    "Finnish": "https://flagsapi.com/FI/flat/64.png",
    "Japanese": "https://flagsapi.com/JP/flat/64.png",
    "French": "https://flagsapi.com/FR/flat/64.png",
    "Polish": "https://flagsapi.com/PL/flat/64.png",
    "Brazilian": "https://flagsapi.com/BR/flat/64.png",
    "Italian": "https://flagsapi.com/IT/flat/64.png",
    "Austrian": "https://flagsapi.com/AT/flat/64.png",
    "American": "https://flagsapi.com/US/flat/64.png",
    "Dutch": "https://flagsapi.com/NL/flat/64.png",
    "Colombian": "https://flagsapi.com/CO/flat/64.png",
    "Portuguese": "https://flagsapi.com/PT/flat/64.png",
    "Canadian": "https://flagsapi.com/CA/flat/64.png",
    "Indian": "https://flagsapi.com/IN/flat/64.png",
    "Hungarian": "https://flagsapi.com/HU/flat/64.png",
    "Irish": "https://flagsapi.com/IE/flat/64.png",
    "Danish": "https://flagsapi.com/DK/flat/64.png",
    "Argentine": "https://flagsapi.com/AR/flat/64.png",
    "Czech": "https://flagsapi.com/CZ/flat/64.png",
    "Malaysian": "https://flagsapi.com/MY/flat/64.png",
    "Swiss": "https://flagsapi.com/CH/flat/64.png",
    "Australian": "https://flagsapi.com/AU/flat/64.png",
    "Monegasque": "https://flagsapi.com/MC/flat/64.png",
    "Belgian": "https://flagsapi.com/BE/flat/64.png",
    "Swedish": "https://flagsapi.com/SE/flat/64.png",
    "Venezuelan": "https://flagsapi.com/VE/flat/64.png",
    "New Zealander": "https://flagsapi.com/NZ/flat/64.png",
    "Chilean": "https://flagsapi.com/CL/flat/64.png",
    "Mexican": "https://flagsapi.com/MX/flat/64.png",
    "South African": "https://flagsapi.com/ZA/flat/64.png",
    "Liechtensteiner": "https://flagsapi.com/LI/flat/64.png",
    "Rhodesian": "https://flagsapi.com/ZW/flat/64.png",
    "Uruguayan": "https://flagsapi.com/UY/flat/64.png",
    "Argentine-Italian": "https://flagsapi.com/IT/flat/64.png",
    "Thai": "https://flagsapi.com/TH/flat/64.png",
    "East German": "https://flagsapi.com/DE/flat/64.png",
    "Argentinian": "https://flagsapi.com/AR/flat/64.png",
    "Indonesian": "https://flagsapi.com/ID/flat/64.png",
    "Russian": "https://flagsapi.com/RU/flat/64.png",
    "Hong Kong": "https://flagsapi.com/HK/flat/64.png",
    "American-Italian": "https://flagsapi.com/IT/flat/64.png",
}

countryFlags = {
    "Australia": "https://flagsapi.com/AU/flat/64.png",
    "Malaysia": "https://flagsapi.com/MY/flat/64.png",
    "Bahrain": "https://flagsapi.com/BH/flat/64.png",
    "Spain": "https://flagsapi.com/ES/flat/64.png",
    "Turkey": "https://flagsapi.com/TR/flat/64.png",
    "Monaco": "https://flagsapi.com/MC/flat/64.png",
    "Canada": "https://flagsapi.com/CA/flat/64.png",
    "France": "https://flagsapi.com/FR/flat/64.png",
    "UK": "https://flagsapi.com/GB/flat/64.png",
    "Germany": "https://flagsapi.com/DE/flat/64.png",
    "Hungary": "https://flagsapi.com/HU/flat/64.png",
    "Belgium": "https://flagsapi.com/BE/flat/64.png",
    "Italy": "https://flagsapi.com/IT/flat/64.png",
    "Singapore": "https://flagsapi.com/SG/flat/64.png",
    "Japan": "https://flagsapi.com/JP/flat/64.png",
    "China": "https://flagsapi.com/CN/flat/64.png",
    "Brazil": "https://flagsapi.com/BR/flat/64.png",
    "USA": "https://flagsapi.com/US/flat/64.png",
    "United States": "https://flagsapi.com/US/flat/64.png",
    "UAE": "https://flagsapi.com/AE/flat/64.png",
    "Argentina": "https://flagsapi.com/AR/flat/64.png",
    "Portugal": "https://flagsapi.com/PT/flat/64.png",
    "South Africa": "https://flagsapi.com/ZA/flat/64.png",
    "Mexico": "https://flagsapi.com/MX/flat/64.png",
    "Korea": "https://flagsapi.com/KR/flat/64.png",
    "Netherlands": "https://flagsapi.com/NL/flat/64.png",
    "Sweden": "https://flagsapi.com/SE/flat/64.png",
    "Austria": "https://flagsapi.com/AT/flat/64.png",
    "Morocco": "https://flagsapi.com/MA/flat/64.png",
    "Switzerland": "https://flagsapi.com/CH/flat/64.png",
    "India": "https://flagsapi.com/IN/flat/64.png",
    "Russia": "https://flagsapi.com/RU/flat/64.png",
    "Azerbaijan": "https://flagsapi.com/AZ/flat/64.png",
    "Saudi Arabia": "https://flagsapi.com/SA/flat/64.png",
    "Qatar": "https://flagsapi.com/QA/flat/64.png",
}