FROM python:3.12.9-alpine3.21

WORKDIR /f1-confia

COPY .docker/requirements.txt .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]